server:  
  port: ${PORT:2222}

spring:  
  application:
    name: graphite-service
  datasource:
    url: jdbc:mysql://192.168.99.100:33306/grafana?useSSL=false
    username: grafana
    password: grafana
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl.auto: update

logging:
  level:
    org.influxdb: DEBUG
    
management:
  endpoint.prometheus.enabled: true
  metrics:
    export:
      influx:
        db: grafana
        uri: http://192.168.99.100:8086
    web.server.auto-time-requests: true
  endpoints.web.exposure.include: '*'